package:
  name: snuggs
  version: "1.3.0"

source:
  fn: snuggs-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/s/snuggs/snuggs-1.3.0.tar.gz
  md5: e672ad353eb2f0a2f8a832e61b99ffb9

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - click
    - numpy
    - pyparsing

  run:
    - python
    - click
    - numpy
    - pyparsing

test:
  imports:
    - snuggs

about:
  home: https://github.com/mapbox/snuggs
  license: MIT
  summary: Snuggs are s-expressions for Numpy
