package:
  name: fiona
  version: !!str 1.1.2

source:
  git_url: https://github.com/Toblerity/Fiona.git
  git_tag: 1.1.2

build:
  number: 0

requirements:
  build:
    - python
    - six
    - gdal
    - cython

  run:
    - python
    - six
    - gdal

test:
  imports:
    - fiona

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD License
  summary: "Fiona is OGR's neat, nimble, no-nonsense API"
