package:
  name: gensim
  version: !!str 0.10.0

source:
  fn: gensim-0.10.0.tar.gz
  url: https://pypi.python.org/packages/source/g/gensim/gensim-0.10.0.tar.gz
  md5: 24ccbf607e4e2a705597627ab6cdba00

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - scipy >=0.7.0
    - six >=1.2.0

  run:
    - python
    - scipy >=0.7.0
    - six >=1.2.0

test:
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.test

about:
  home: http://radimrehurek.com/gensim
  license:  GNU Library or Lesser General Public License (LGPL)
  summary: 'Python framework for fast Vector Space Modelling'
