package:
  name: pygridgen
  version: !!str 0.1

source:
  git_url: https://github.com/phobson/pygridgen.git
  git_tag: develop

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - basemap
    - numpy
    - nose

  run:
    - python
    - pandas
    - numpy
    - matplotlib
    - basemap
    - nose

test:
  imports:
    - pygridgen

  commands:
    - nosetests

  requires:
   - nose

about:
  home: https://github.com/hetland/pygridgen.git
  license:  BSD License
  summary: 'Python interface to gridgen by Pavel Sakov'
