package:
  name: tappy
  version: !!str 0.9.0

source:
  fn: tappy-0.9.0.tar.gz
  url: http://downloads.sourceforge.net/tappy/tappy-0.9.0.tar.gz
  md5: dadb5a083b2a77dadf3639d47ea6b9cc

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy
  run:
    - python
    - numpy
    - scipy

about:
  home: http://sourceforge.net/p/tappy/wiki/Main_Page/
  license: MIT
  summary: 'Tidal Analysis Program in PYthon'
