package:
    name: folium
    version: "0.1.4"

source:
    fn: folium-0.1.4.tar.gz
    url: https://pypi.python.org/packages/source/f/folium/folium-0.1.4.tar.gz
    md5: b5e0c8eac6f92e9806b91eced8586047

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - jinja2

test:
  imports:
    - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js and Python'
