package:
  name: folium
  version: !!str 0.1.4

source:
  git_url: https://github.com/ocefpaf/folium.git
  git_tag: set_width

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - jinja2

test:
  imports:
    - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js & Python'
