package:
  name: geolinks
  version: !!str 0.1

source:
  git_url: https://github.com/geopython/geolinks.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - geolinks

about:
  home: http://code.google.com/p/geolinks
  license: MIT
  summary: 'Reads and writes ESRI Shapefiles in pure Python.'
