package:
    name: geolinks
    version: "0.0.1"

source:
    fn: geolinks-0.0.1.tar.gz
    url: https://pypi.python.org/packages/source/g/geolinks/geolinks-0.0.1.tar.gz
    md5: 51e43aa0afd611cebc986ec411f24d40

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - geolinks

about:
    home: https://github.com/geopython/geolinks
    license: MIT
    summary: 'Utilities to deal with geospatial links'
