package:
    name: geolinks
    version: "0.1.0"

source:
    fn: geolinks-0.1.0.tar.gz
    url: https://pypi.python.org/packages/source/g/geolinks/geolinks-0.1.0.tar.gz
    md5: c868d699319e8dee7a10f6745441107c

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - geolinks

about:
    home: https://github.com/geopython/geolinks
    license: MIT
    summary: 'Utilities to deal with geospatial links'
