package:
  name: wheel
  version: !!str 0.24.0

source:
  fn: wheel-0.24.0.tar.gz
  url: https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz
  md5: 3b0d66f0d127ea8befaa5d11453107fd

build:
  preserve_egg_dir: True
  entry_points:
    - wheel=wheel.tool:main
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - wheel
    - wheel.signatures
    - wheel.test
    - wheel.tool

  commands:
    - wheel --help

about:
  home: http://bitbucket.org/pypa/wheel/
  license: MIT
  summary: 'A built-package format for Python.'
