package:
  name: mpld3
  version: !!str 0.2

source:
  fn: mpld3-0.2.tar.gz
  url: https://pypi.python.org/packages/source/m/mpld3/mpld3-0.2.tar.gz
  md5: 266f4e51a094f8ff1aaf7e2018f763b4

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jinja2
    - matplotlib

test:
  imports:
    - mpld3

about:
  home: http://mpld3.github.com
  license: BSD License
  summary: 'D3 Viewer for Matplotlib'
