language: c

os:
  - linux
  - osx

env:
  global:
  - secure: RRgRpMfKIVswcs0rBbW9jjNmk3MEvpxoyiI/9k9u6d2PyiklP7jqcepsfD9pCpgw0PPf5jR1aeT8B01HxTV5Pp7rA7kEAco1XmTsdWugxkKGLolJMw4vzAJBfRJYLzPfFFPvhaHw1EW/AY83c6RqNoDBHPCK+VID3XosXTfzqFM=
    matrix:
  - CONDA_PY=27  CONDA_NPY=18

install:
  - if [[ "$OSTYPE" == "linux-gnu" ]]; then sudo apt-get install texinfo; fi
  - wget https://raw.githubusercontent.com/pelson/Obvious-CI/v0.1.0/bootstrap-obvious-ci-and-miniconda.py
  - python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root
  - conda config --set show_channel_urls True && conda config --add channels http://conda.binstar.org/ocefpaf/channel/main
  - conda install -c http://conda.binstar.org/pelson/channel/development --yes --quiet obvious-ci
  - conda config --add channels http://conda.binstar.org/ocefpaf
  - obvci_install_conda_build_tools.py

script:
  - obvci_conda_build_dir.py ./ ocefpaf --channel main
