package:
    name: scp
    version: "0.9.0"

source:
    fn: scp-0.9.0.tar.gz
    url: https://pypi.python.org/packages/source/s/scp/scp-0.9.0.tar.gz
    md5: 47f5837425c05dae9f79123c105ee2dd

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - paramiko
    run:
        - python
        - paramiko

test:
    imports:
        - scp

about:
    home: https://github.com/jbardin/scp.py.git
    license: LGPL
    summary: 'scp module for paramiko'
