package:
  name: pyoos
  version: !!str 0.6.2

source:
  git_url: https://github.com/ioos/pyoos.git
  git_tag: 0.6.2

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - numpy
    - paegan
    - owslib
    - requests
    - fiona
    - beautifulsoup4
    - lxml
    - pytest

  run:
    - python
    - paegan
    - owslib
    - numpy
    - requests
    - fiona
    - beautifulsoup4
    - lxml
    - pytest

test:
  imports:
    - tests
    - pyoos.parsers
    - pyoos.collectors.nerrs
    - pyoos.collectors
    - pyoos
    - pyoos.collectors.hads
    - pyoos.collectors.coops
    - pyoos.collectors.ndbc
    - pyoos.parsers.ioos
    - pyoos.collectors.usgs
    - pyoos.collectors.ioos
    - pyoos.parsers.ioos.one
    - pyoos.parsers.wqx
    - pyoos.utils
    - pyoos.collectors.awc
    - pyoos.collectors.wqp
#   - tests.collectors

about:
  home: https://github.com/asascience-open/pyoos
  license: GNU General Public License v3 (GPLv3)
  summary: 'A Python library for collecting Met/Ocean observations'
