package:
  name: workerpool
  version: !!str 0.9.2

source:
  fn: workerpool-0.9.2.tar.gz
  url: https://pypi.python.org/packages/source/w/workerpool/workerpool-0.9.2.tar.gz
  md5: 42904070f1a58f2a7b7276b22134375b

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - workerpool

about:
  home: http://github.com/shazow/workerpool
  license: MIT License
  summary: 'Module for distributing jobs to a pool of worker threads.'
