package:
    name: rdflib
    version: "4.2.0"

source:
    fn: rdflib-4.2.0.tar.gz
    url: https://pypi.python.org/packages/source/r/rdflib/rdflib-4.2.0.tar.gz
    md5: ac6f02229bfb1882d743de496268f8d8

build:
    number: 0
    entry_points:
        - rdfpipe = rdflib.tools.rdfpipe:main
        - csv2rdf = rdflib.tools.csv2rdf:main
        - rdf2dot = rdflib.tools.rdf2dot:main
        - rdfs2dot = rdflib.tools.rdfs2dot:main
        - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main

requirements:
    build:
        - python
        - setuptools
        - pip
        - isodate
        - pyparsing
        # NOTE: Using pip in build.sh/bld.bat to avoid circular dependency.
        # - sparqlwrapper
        - html5lib
        - six
    run:
        - python
        - setuptools
        - isodate
        - pyparsing
        # NOTE: Using pip in build.sh/bld.bat to avoid circular dependency.
        # - sparqlwrapper
        - html5lib
        - six

test:
    imports:
        - rdflib
        - rdflib.namespace
    commands:
        - rdfpipe --help

about:
    home: https://github.com/RDFLib/rdflib
    license: BSD License
    summary: 'RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information'
