package:
  name: utilities
  version: "0.2.2"

source:
  git_url: https://github.com/pyoceans/utilities.git
  git_tag: v0.2.2

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - iris
    - lxml
    - pandas
    - beautifulsoup4
    - folium
    - ipython-notebook
    - oceans
    - pyugrid  # [not win]
    - owslib
    - requests
test:
  imports:
    - utilities

about:
  home: https://github.com/ocefpaf/utilities.git
  license: MIT License
  summary: "IOOS/SECOORA `utilities.py` module."
