package:
  name: oceans
  version: !!str 0.2.3

source:
  fn: oceans-0.2.3.tar.gz
  url: https://pypi.python.org/packages/source/o/oceans/oceans-0.2.3.tar.gz
  md5: d5a39536c2bf184dfc2a77327cb2ca70

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8
    - scipy >=0.13
    - matplotlib >=1.2
    - pandas >=0.13
    - gsw >=3.0.2
    - seawater
    - shapely
    - netcdf4
    - ctd

  run:
    - python
    - numpy >=1.8
    - scipy >=0.13
    - matplotlib >=1.2
    - pandas >=0.13
    - gsw >=3.0.2
    - seawater
    - shapely
    - netcdf4
    - ctd

test:
  imports:
    - oceans

about:
  home: http://pypi.python.org/pypi/oceans/
  license: MIT License
  summary: 'Misc functions for oceanographic data analysis'
