package:
  name: gridgen
  version: 1.48

source:
  git_url: https://github.com/phobson/gridgen.git
  git_tag: master

build:
  number: 0

requirements:
  build:
   - gridutils

about:
  home: https://code.google.com/p/gridgen-c
  license: MIT License
  summary: "Pavel Sakov's curvilinear orthogonal grid generation library."
