package:
  name: nn
  version: 1.85

source:
  git_url: https://github.com/phobson/nn.git

build:
  number: 0

about:
  home: https://code.google.com/p/nn-c
  license: MIT License
  summary: "Pavel Sakov's natural neighbors library"
