package:
  name: folium
  version: "0.1.4.dev"

source:
  git_url: https://github.com/python-visualization/folium.git
  git_tag: master

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - jinja2

test:
  imports:
    - folium

about:
  home: https://github.com/wrobstory/folium
  license: MIT License
  summary: 'Make beautiful maps with Leaflet.js and Python'
