package: mplleaflet

user: ocefpaf

platform:
  - linux-64
engine:
  - python=2

before_script:
  - conda config --set show_channel_urls True
  - conda config --add channels ocefpaf/channel/dev
script:
  - conda build .

after_success:
  - echo "after_success!"
after_failure:
  - echo "after_failure!"

build_targets:
  - conda
