package:
    name: setproctitle
    version: "1.1.8"

source:
    fn: setproctitle-1.1.8.tar.gz
    url: https://pypi.python.org/packages/source/s/setproctitle/setproctitle-1.1.8.tar.gz
    md5: 728f4c8c6031bbe56083a48594027edd

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - setproctitle

about:
    home: http://code.google.com/p/py-setproctitle/
    license: BSD License
    summary: 'A library to allow customization of the process title.'
