package:
    name: coveralls
    version: "1.0a2"

source:
    fn: coveralls-1.0a2.tar.gz
    url: https://pypi.python.org/packages/source/c/coveralls/coveralls-1.0a2.tar.gz
    md5: 678eb7fdd3d477a4d9d0cacbffe88ee2

build:
    number: 0
    entry_points:
        - coveralls = coveralls.cli:main

requirements:
    build:
        - python
        - setuptools
        - docopt >=0.6.1
        - coverage >=3.6
        - requests >=1.0.0
    run:
        - python
        - setuptools
        - docopt >=0.6.1
        - coverage >=3.6
        - requests >=1.0.0

test:
    imports:
        - coveralls
    commands:
        - coveralls --help

about:
    home: http://github.com/coagulant/coveralls-python
    license: MIT License
    summary: 'Show coverage stats online via coveralls.io'
