package:
  name: pymc
  version: !!str 2.3.3

source:
  fn: pymc-2.3.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pymc/pymc-2.3.3.tar.gz
  md5: 99645bf558a41376be0e687ccf90a39f

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - pymc

about:
  home: http://github.com/pymc-devs/pymc
  license:  Academic Free License (AFL)
  summary: 'Markov Chain Monte Carlo sampling toolkit.'
