package:
    name: obvious-ci
    version: '0.2.dev'

source:
    git_url: https://github.com/pelson/Obvious-CI.git

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - binstar
        - conda
        - conda-build

about:
    home: https://github.com/pelson/Obvious-CI
    license: GPL
    summary: Simplify the implementation of continuous integration such as Travis CI and appveyor.
