package:
  name: mysql-python
  version: !!str 1.2.5

source:
  fn: MySQL-python-1.2.5.zip
  url: https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.5.zip
  md5: 654f75b302db6ed8dc5a898c625e030c

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/farcepest/MySQLdb1
  license: GNU General Public License (GPL)
  summary: 'Python interface to MySQL'
