package:
  name: pygdp
  version: !!str 1.2.2

source:
  git_url: https://github.com/USGS-CIDA/pyGDP.git
  git_tag: v1.2.2

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - owslib
  run:
    - python
    - owslib

test:
  imports:
    - pyGDP

about:
  home: https://github.com/USGS-CIDA/pyGDP
  license: CC0
  summary: 'python interface to facilitate working with USGS-CIDA Geo Data Portal web services'
