package:
    name: click
    version: "4.0"

source:
    git_url: https://github.com/mitsuhiko/click.git
    git_tag: 4.0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - click

about:
    home: http://github.com/mitsuhiko/click
    license:  BSD License
    summary: 'A simple wrapper around optparse for powerful command line utilities.'
