package:
  name: rtree
  version: "0.8.1"

source:
  git_url: https://github.com/Toblerity/rtree.git
  git_tag: 0.8.1

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - libspatialindex

  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree

about:
  home: http://toblerity.github.com/rtree/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'R-Tree spatial index for Python GIS'
