package:
    name: isodate
    version: "0.5.1"

source:
    fn: isodate-0.5.1.tar.gz
    url: https://pypi.python.org/packages/source/i/isodate/isodate-0.5.1.tar.gz
    md5: 22232a6b0f5d320610ae45722c1b9542

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - isodate
        - isodate.tests

about:
    home: http://cheeseshop.python.org/pypi/isodate
    license: BSD License
    summary: 'An ISO 8601 date/time/duration parser and formatter'
