package:
  name: beautifulsoup4
  version: !!str 4.3.2

source:
  fn: beautifulsoup4-4.3.2.tar.gz
  url: https://pypi.python.org/packages/source/b/beautifulsoup4/beautifulsoup4-4.3.2.tar.gz
  md5: b8d157a204d56512a4cc196e53e7d8ee

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - bs4
    - bs4.builder
    - bs4.tests

about:
  home: http://www.crummy.com/software/BeautifulSoup/bs4/
  license: MIT License
  summary: 'Beautiful Soup sits atop an HTML or XML parser, providing Pythonic idioms for iterating, searching, and modifying the parse tree'
