package:
  name: enum34
  version: !!str 1.0

source:
  fn: enum34-1.0.tar.gz
  url: https://pypi.python.org/packages/source/e/enum34/enum34-1.0.tar.gz
  md5: 9d57f5454c70c11707998ea26c1b0a7c

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - enum

about:
  home: https://pypi.python.org/pypi/enum34
  license:  BSD License
  summary: 'Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4'
