package:
    name: udunits2
    version: "2.2.19"

source:
    fn: v2.2.19.tar.gz
    url: https://github.com/Unidata/UDUNITS-2/archive/v2.2.19.tar.gz
    sha1: 39ff26ae5186573897254b91e97690c67b96cf89

requirements:
  build:
    - expat  # [win]
  run:
    - expat  # [win]

build:
    number: 0 # [win]
    number: 0 # [not win]
    detect_binary_files_with_prefix: true

test:
    commands:
        - udunits2 -h
        - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  summary: "The UDUNITS package supports units of physical quantities."
