package:
  name: south
  version: "1.0.1"

source:
  fn: South-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/S/South/South-1.0.1.tar.gz
  md5: 9977423e4c4f7ca9345f1428a0a57505

build:
  number: 0

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  imports:
    - south

about:
  home: http://south.aeracode.org/
  license: Apache Software License
