package:
    name: pytest-cov
    version: !!str 1.8.1

source:
    fn: pytest-cov-1.8.1.tar.gz
    url: https://pypi.python.org/packages/source/p/pytest-cov/pytest-cov-1.8.1.tar.gz
    md5: 76c778afa2494088270348be42d759fc

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - pytest >=2.5.2
        - cov-core >=1.12
    run:
        - python
        - pytest >=2.5.2
        - cov-core >=1.12

about:
    home: https://github.com/schlamar/pytest-cov
    license:  MIT License
    summary: 'py.test plugin for coverage reporting with support for both centralised and distributed testing, including subprocesses and multiprocessing'
