package:
  name: prettyplotlib
  version: !!str 0.1.7

source:
  fn: prettyplotlib-0.1.7.tar.gz
  url: https://pypi.python.org/packages/source/p/prettyplotlib/prettyplotlib-0.1.7.tar.gz
  md5: 85e4d27cefb86d5b2161eff94a77a7bc

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - matplotlib >=1.2.1
    - brewer2mpl >=1.3.1

  run:
    - python
    - matplotlib >=1.2.1
    - brewer2mpl >=1.3.1

test:
  imports:
    - prettyplotlib

about:
  home: http://olgabot.github.io/prettyplotlib
  license: MIT License
  summary: 'Painlessly create beautiful default `matplotlib` plots'
