package:
  name: starcluster
  version: !!str 0.95.6

source:
  fn: StarCluster-0.95.6.tar.gz
  url: https://pypi.python.org/packages/source/S/StarCluster/StarCluster-0.95.6.tar.gz
  md5: efec9d81232f933af4609e81aa11152e

build:
  entry_points:
    - starcluster = starcluster.cli:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - paramiko >=1.12.1
    - boto >=2.23.0
    - workerpool >=0.9.2
    - jinja2 >=2.7
    - decorator >=3.4.0
    - iptools >=0.6.1
    - optcomplete >=1.2-devel
    - pycrypto >=2.5
    - scp >=0.7.1
    - iso8601 >=0.1.8

  run:
    - python
    - paramiko >=1.12.1
    - boto >=2.23.0
    - workerpool >=0.9.2
    - jinja2 >=2.7
    - decorator >=3.4.0
    - iptools >=0.6.1
    - optcomplete >=1.2-devel
    - pycrypto >=2.5
    - scp >=0.7.1
    - iso8601 >=0.1.8

test:
  imports:
    - starcluster
    - starcluster.balancers
    - starcluster.balancers.sge
    - starcluster.commands
    - starcluster.plugins
    - starcluster.templates
    - starcluster.tests
    - starcluster.tests.templates

  commands:
    - starcluster --help

about:
  home: http://star.mit.edu/cluster
  license: GNU Library or Lesser General Public License (LGPL)
  summary: "StarCluster is a utility for creating and managing computing clusters hosted on Amazon's Elastic Compute Cloud (EC2)."
