package:
  name: petulant-bear
  version: !!str 0.1.2

source:
  fn: petulant-bear-0.1.2.tar.gz
  url: https://pypi.python.org/packages/source/p/petulant-bear/petulant-bear-0.1.2.tar.gz
  md5: 2b71e5a00d9d7aff70284dffc3be2f13

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - netcdf4 >=1.0.0
    - nose >=1.2.0
    - numpy
    - lxml >=3.2.1

  run:
    - python
    - netcdf4 >=1.0.0
    - nose >=1.2.0
    - numpy
    - lxml >=3.2.1

test:
  imports:
    - petulantbear

about:
  home: https://github.com/ioos/petulant-bear
  license:  GNU General Public License v3 (GPLv3)
  summary: 'Presents etree interface to netcdf4-python objects using NCML data model'
