package:
  name: delocate
  version: !!str 0.6.2

source:
  fn: delocate-0.6.2.zip
  url: https://pypi.python.org/packages/source/d/delocate/delocate-0.6.2.zip
  md5: 521d40dd552bf4ad05c11eef58f7ab26

build:
  number: 0

requirements:
  build:
    - python
    - wheel
    - setuptools
  run:
    - python
    - wheel

test:
  imports:
    - delocate
    - delocate.tests

about:
  home: http://github.com/matthew-brett/delocate
  license: BSD License
  summary: 'Move OSX dynamic libraries into package'
