package:
  name: iptools
  version: !!str 0.6.1

source:
  fn: iptools-0.6.1.tar.gz
  url: https://pypi.python.org/packages/source/i/iptools/iptools-0.6.1.tar.gz
  md5: aed4045638fd40c16f8d9bb04606f700

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - iptools

about:
  home: https://github.com/bd808/python-iptools
  license: BSD License
  summary: 'Python utilites for manipulating IPv4 and IPv6 addresses'
