package:
  name: airsea
  version: !!str 0.0.1_DEV

source:
    git_url: https://github.com/ocefpaf/python-airsea.git
    git_tag: master

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - airsea

about:
  home: http://github.com/ocefpaf/python-airsea
  license: MIT License
  summary: 'Airsea Library for Python'
