package:
  name: affine
  version: "1.1.0"

source:
  fn: affine-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/a/affine/affine-1.1.0.tar.gz
  md5: a3d020a8f0ebb762294caf0cc5d28d18

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - affine

about:
  home: https://github.com/sgillies/affine
  license:  BSD License
  summary: 'Matrices describing affine transformation of the plane'
