package:
  name: pyproj
  version: "1.9.4"

source:
  fn: pyproj-1.9.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pyproj/pyproj-1.9.4.tar.gz
  md5: b0a060465b117dd6c1b37e14f22382aa

build:
  number: 0

requirements:
  build:
    - python
    - cython

  run:
    - python
    - proj4
    - numpy
test:
  imports:
    - pyproj

about:
  home: http://code.google.com/p/pyproj/
  license: OSI
