package:
  name: pyproj
  version: !!str 1.9.3

source:
  fn: pyproj-1.9.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pyproj/pyproj-1.9.3.tar.gz
  md5: ad0ac0602b6373c4203b4d0774445694

build:
  number: 0

requirements:
  build:
    - python
    - cython

  run:
    - python
    - proj4
    - numpy
test:
  imports:
    - pyproj

about:
  home: http://code.google.com/p/pyproj/
  license: OSI
